# cloud_config
write_files: 
  - path: /etc/server.conf
    owners: root:root
    permissions:  "0644"
    content: |
      {
        "user": "${user}"
        "password": "${password}"
        "database": "${database}"
        "netloc": "${hostname}:${port}"
      }
runcmd: 
  - curl -sL https://api.github.com/repos/terraform-in-action/vanilla-webserver-src/releases/latest | jq -r ".assets[].browser_download_url" | wget -qi -
  - unzip deployment.zip
  - ./deployment/server

packages: 
  - jq
  - wget
  - unzip